HOST: http://api.bushfir.es/

# Fire incidents API
An API to current and previous [RFS](http://www.rfs.nsw.gov.au) major incidents.

# GET /incidents
Retrieve a collection of incidents which may or may not be filtered by parameters included in the request.

+ Parameters

    + current = `true` (optional, boolean) ... Boolean value indicating whether to only include current incidents or not.

+ Response 200 (application/json)

  JSON conforming to the GeoJSON spec. Response is a feature collection containing 0 or more features. Each feature represents an incident. Properties included in the feature object are taken from the incident's most recent report.

  + Body

            {
              "type": "FeatureCollection",
              "features": [
                {
                  "type": "Feature",
                  "id": "0830647b-43c5-4641-96c8-bbb2a306c23f",
                  "geometry": {
                    "type": "Point",
                    "coordinates": [
                      "151.6034",
                      "-33.1567"
                    ]
                  },
                  "properties": {
                    "reportUuid": "ea1c0c1f-df33-4e7d-bc64-70ca77500ea6",
                    "guid": "tag:www.rfs.nsw.gov.au,2014-05-20:84431",
                    "title": "Crangan Bay-West Coal Fire",
                    "link": "http:\/\/www.rfs.nsw.gov.au\/dsp_content.cfm?cat_id=683",
                    "category": "Advice",
                    "pubdate": "2014-05-20T00:00:00Z",
                    "firstSeen": "2013-11-30T06:48:00Z",
                    "lastSeen": "2014-05-20T00:00:00Z",
                    "alertLevel": "Advice",
                    "location": "500 metres west of Pacific Hwy at Crangan Bay. Same location as previous Incident - No 13113083624.",
                    "councilArea": "Lake Macquarie",
                    "status": "under control",
                    "fireType": "Scrub fire",
                    "fire": true,
                    "size": "0 ha",
                    "responsibleAgency": "NSW National Parks and Wildlife Service",
                    "extra": ""
                  }
                }
              ]
            }

# GET /incidents/{id}
Retrieve an incident by its *id*.

+ Parameters

    + id (required, string, `df34a81e-4fe5-4c09-8403-466526ea503c`) ... Id of an incident.

+ Response 200 (application/json)

  JSON conforming to the GeoJSON spec. Response is a feature representing the requested incident. Properties included in the feature object are taken from the incident's most recent report.

  + Body

            {
              "type": "Feature",
              "id": "0830647b-43c5-4641-96c8-bbb2a306c23f",
              "geometry": {
                "type": "Point",
                "coordinates": [
                  "151.6034",
                  "-33.1567"
                ]
              },
              "properties": {
                "reportUuid": "ea1c0c1f-df33-4e7d-bc64-70ca77500ea6",
                "guid": "tag:www.rfs.nsw.gov.au,2014-05-20:84431",
                "title": "Crangan Bay-West Coal Fire",
                "link": "http:\/\/www.rfs.nsw.gov.au\/dsp_content.cfm?cat_id=683",
                "category": "Advice",
                "pubdate": "2014-05-20T00:00:00Z",
                "firstSeen": "2013-11-30T06:48:00Z",
                "lastSeen": "2014-05-20T00:00:00Z",
                "alertLevel": "Advice",
                "location": "500 metres west of Pacific Hwy at Crangan Bay. Same location as previous Incident - No 13113083624.",
                "councilArea": "Lake Macquarie",
                "status": "under control",
                "fireType": "Scrub fire",
                "fire": true,
                "size": "0 ha",
                "responsibleAgency": "NSW National Parks and Wildlife Service",
                "extra": ""
              }
            }

