HOST: http://api.bushfir.es/

# Fire incidents API
An API to current and previous [RFS](http://www.rfs.nsw.gov.au) major incidents.

# GET /incidents
Retrieve a collection of incidents. Currently, in lieu of pagination, a time range is required for all requests.

+ Parameters

    + timeStart (required, timestamp, `2014-01-01T00:00:00Z`) ... Start of time range in UTC
    + timeEnd (required, timestamp, `2014-01-31T23:59:59Z`) ... End of time range in UTC

+ Response 200 (application/json)

  JSON conforming to the GeoJSON spec. Response is a `FeatureCollection` containing 0 or more features. Each `Feature` represents an incident. Properties included in the feature object are taken from the incident's most recent report.

  This endpoint has the ablity to return very large responses. In the interest of performance, the features within the response contain minimal information. They will not include geographic polygons and all of an incident's properties. They will include coordinates for the incident and an ID for retrieving all of the incident's details.

  The incidents included in the response are those that were `current` within the requested time range. E.g if you request one day's worth, it may include incidents that were current for an hour during that day, some that had been current for days beforehand but finished on that day, and some that were current for many days before and after.

  + Body

            {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "id": "0ee1fd01-11bc-4526-8910-5423e63e898c",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [
                                151.6034,
                                -33.1567
                            ]
                        },
                        "properties": {
                            "title": "Crangan Bay -West",
                            "link": "http://www.rfs.nsw.gov.au/dsp_content.cfm?cat_id=683",
                            "fireType": "Scrub fire"
                        }
                    },
                    {
                        "type": "Feature",
                        "id": "176a2772-2589-4fa5-bb21-16af5bcd69fc",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [
                                145.9021,
                                -30.0348
                            ]
                        },
                        "properties": {
                            "title": "Darling Farms",
                            "link": "http://www.rfs.nsw.gov.au/dsp_content.cfm?cat_id=683",
                            "fireType": "Scrub fire"
                        }
                    }
                ]
              }

# GET /incidents/current
Retrieve a collection of current incidents. Current incidents are those that were present in the RFS current incidents feed at the last scheduled import.

+ Response 200 (application/json)

  JSON conforming to the GeoJSON spec. Response is a `FeatureCollection` containing 0 or more `features`. Each `Feature` represents an incident. Properties included in the feature object are taken from the incident's most recent report.

  + Body

            {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "id": "0ee1fd01-11bc-4526-8910-5423e63e898c",
                        "geometry": {
                            "type": "GeometryCollection",
                            "geometries": [
                                {
                                    "type": "Point",
                                    "coordinates": [
                                        151.6034,
                                        -33.1567
                                    ]
                                }
                            ]
                        },
                        "properties": {
                            "reportUuid": "16d9c09c-aba0-47ce-964f-01aa75b1af10",
                            "guid": "tag:www.rfs.nsw.gov.au,2013-12-31:84431",
                            "title": "Crangan Bay -West",
                            "link": "http://www.rfs.nsw.gov.au/dsp_content.cfm?cat_id=683",
                            "category": "Advice",
                            "pubdate": "2013-12-31T05:00:00Z",
                            "firstSeen": "2013-11-30T06:48:00Z",
                            "lastSeen": "2013-12-31T05:00:00Z",
                            "alertLevel": "Advice",
                            "location": "500 metres west of Pacific Hwy at Crangan Bay. Same location as previous Incident - No 13113083624.",
                            "councilArea": "Lake Macquarie",
                            "status": "under control",
                            "fireType": "Scrub fire",
                            "fire": true,
                            "size": "0 ha",
                            "responsibleAgency": "Rural Fire Service",
                            "extra": ""
                        }
                    },
                    {
                        "type": "Feature",
                        "id": "176a2772-2589-4fa5-bb21-16af5bcd69fc",
                        "geometry": {
                            "type": "GeometryCollection",
                            "geometries": [
                                {
                                    "type": "Point",
                                    "coordinates": [
                                        145.9021,
                                        -30.0348
                                    ]
                                },
                                {
                                    "type": "MultiPolygon",
                                    "coordinates": [
                                        [
                                            [
                                                [
                                                    145.9009,
                                                    -30.0399
                                                ],
                                                [
                                                    145.8996,
                                                    -30.041
                                                ],
                                                [
                                                    145.8989,
                                                    -30.0391
                                                ],
                                                [
                                                    145.8989,
                                                    -30.039
                                                ],
                                                [
                                                    145.9003,
                                                    -30.0366
                                                ],
                                                [
                                                    145.8992,
                                                    -30.0351
                                                ],
                                                [
                                                    145.8993,
                                                    -30.0342
                                                ],
                                                [
                                                    145.9,
                                                    -30.0329
                                                ],
                                                [
                                                    145.9013,
                                                    -30.0312
                                                ],
                                                [
                                                    145.9024,
                                                    -30.0305
                                                ],
                                                [
                                                    145.9023,
                                                    -30.0296
                                                ],
                                                [
                                                    145.9024,
                                                    -30.0291
                                                ],
                                                [
                                                    145.9031,
                                                    -30.0284
                                                ],
                                                [
                                                    145.9036,
                                                    -30.0287
                                                ],
                                                [
                                                    145.9043,
                                                    -30.0292
                                                ],
                                                [
                                                    145.905,
                                                    -30.0297
                                                ],
                                                [
                                                    145.9052,
                                                    -30.0303
                                                ],
                                                [
                                                    145.9053,
                                                    -30.0306
                                                ],
                                                [
                                                    145.9052,
                                                    -30.0316
                                                ],
                                                [
                                                    145.905,
                                                    -30.0325
                                                ],
                                                [
                                                    145.9048,
                                                    -30.0333
                                                ],
                                                [
                                                    145.9046,
                                                    -30.0345
                                                ],
                                                [
                                                    145.9048,
                                                    -30.0353
                                                ],
                                                [
                                                    145.9032,
                                                    -30.0369
                                                ],
                                                [
                                                    145.9027,
                                                    -30.0375
                                                ],
                                                [
                                                    145.9021,
                                                    -30.0382
                                                ],
                                                [
                                                    145.9018,
                                                    -30.0388
                                                ],
                                                [
                                                    145.9014,
                                                    -30.0391
                                                ],
                                                [
                                                    145.9009,
                                                    -30.0399
                                                ]
                                            ]
                                        ]
                                    ]
                                }
                            ]
                        },
                        "properties": {
                            "reportUuid": "7872b6a4-2730-4ef8-9e3a-4fa4582cc3df",
                            "guid": "tag:www.rfs.nsw.gov.au,2013-12-31:151096",
                            "title": "Darling Farms",
                            "link": "http://www.rfs.nsw.gov.au/dsp_content.cfm?cat_id=683",
                            "category": "Advice",
                            "pubdate": "2013-12-31T04:00:00Z",
                            "firstSeen": "2013-12-30T03:05:00Z",
                            "lastSeen": "2013-12-31T04:00:00Z",
                            "alertLevel": "Advice",
                            "location": "North Bourke",
                            "councilArea": "Bourke",
                            "status": "under control",
                            "fireType": "Scrub fire",
                            "fire": true,
                            "size": "45 ha",
                            "responsibleAgency": "Rural Fire Service",
                            "extra": ""
                        }
                    }
                ]
              }

# GET /incidents/{id}
Retrieve an incident by its *id*.

+ Parameters

    + id (required, string, `df34a81e-4fe5-4c09-8403-466526ea503c`) ... Id of an incident.

+ Response 200 (application/json)

  JSON conforming to the GeoJSON spec. Response is a `Feature` representing the requested incident. Properties included in the feature object are taken from the incident's most recent report.

  + Body

            {
                "type": "Feature",
                "id": "176a2772-2589-4fa5-bb21-16af5bcd69fc",
                "geometry": {
                    "type": "GeometryCollection",
                    "geometries": [
                        {
                            "type": "Point",
                            "coordinates": [
                                145.9021,
                                -30.0348
                            ]
                        },
                        {
                            "type": "MultiPolygon",
                            "coordinates": [
                                [
                                    [
                                        [
                                            145.9009,
                                            -30.0399
                                        ],
                                        [
                                            145.8996,
                                            -30.041
                                        ],
                                        [
                                            145.8989,
                                            -30.0391
                                        ],
                                        [
                                            145.8989,
                                            -30.039
                                        ],
                                        [
                                            145.9003,
                                            -30.0366
                                        ],
                                        [
                                            145.8992,
                                            -30.0351
                                        ],
                                        [
                                            145.8993,
                                            -30.0342
                                        ],
                                        [
                                            145.9,
                                            -30.0329
                                        ],
                                        [
                                            145.9013,
                                            -30.0312
                                        ],
                                        [
                                            145.9024,
                                            -30.0305
                                        ],
                                        [
                                            145.9023,
                                            -30.0296
                                        ],
                                        [
                                            145.9024,
                                            -30.0291
                                        ],
                                        [
                                            145.9031,
                                            -30.0284
                                        ],
                                        [
                                            145.9036,
                                            -30.0287
                                        ],
                                        [
                                            145.9043,
                                            -30.0292
                                        ],
                                        [
                                            145.905,
                                            -30.0297
                                        ],
                                        [
                                            145.9052,
                                            -30.0303
                                        ],
                                        [
                                            145.9053,
                                            -30.0306
                                        ],
                                        [
                                            145.9052,
                                            -30.0316
                                        ],
                                        [
                                            145.905,
                                            -30.0325
                                        ],
                                        [
                                            145.9048,
                                            -30.0333
                                        ],
                                        [
                                            145.9046,
                                            -30.0345
                                        ],
                                        [
                                            145.9048,
                                            -30.0353
                                        ],
                                        [
                                            145.9032,
                                            -30.0369
                                        ],
                                        [
                                            145.9027,
                                            -30.0375
                                        ],
                                        [
                                            145.9021,
                                            -30.0382
                                        ],
                                        [
                                            145.9018,
                                            -30.0388
                                        ],
                                        [
                                            145.9014,
                                            -30.0391
                                        ],
                                        [
                                            145.9009,
                                            -30.0399
                                        ]
                                    ]
                                ]
                            ]
                        }
                    ]
                },
                "properties": {
                    "reportUuid": "7872b6a4-2730-4ef8-9e3a-4fa4582cc3df",
                    "guid": "tag:www.rfs.nsw.gov.au,2013-12-31:151096",
                    "title": "Darling Farms",
                    "link": "http://www.rfs.nsw.gov.au/dsp_content.cfm?cat_id=683",
                    "category": "Advice",
                    "pubdate": "2013-12-31T04:00:00Z",
                    "firstSeen": "2013-12-30T03:05:00Z",
                    "lastSeen": "2013-12-31T04:00:00Z",
                    "alertLevel": "Advice",
                    "location": "North Bourke",
                    "councilArea": "Bourke",
                    "status": "under control",
                    "fireType": "Scrub fire",
                    "fire": true,
                    "size": "45 ha",
                    "responsibleAgency": "Rural Fire Service",
                    "extra": ""
                }
            }

# GET /incidents/{id}/reports
Retrieve all reports for a specified incident.

+ Parameters

    + id (required, string, `df34a81e-4fe5-4c09-8403-466526ea503c`) ... Id of an incident.

+ Response 200 (application/json)

  Reports are returned as a GeoJSON `FeatureCollection` whose `features` are ordered by `pubdate` in ascending order. Each item within the `FeatureCollection` is a `Feature` representing the report. A report is basically a snapshot of the incident at a given time. A report should never be identical to the one preceeding or following it.

  + Body
            {
                "type":"FeatureCollection",
                "features":[
                    {
                        "type":"Feature",
                        "id":"f796f4de-24d3-422f-a197-01c4dffd3276",
                        "geometry":{
                            "type":"GeometryCollection",
                            "geometries":[
                                {
                                    "type":"Point",
                                    "coordinates":[
                                        151.6282,
                                        -31.9785
                                    ]
                                }
                            ]
                        },
                        "properties":{
                            "guid":"tag:www.rfs.nsw.gov.au,2014-11-25:179696",
                            "title":"Moppy Rd, Moppy",
                            "link":"http://www.rfs.nsw.gov.au/dsp_content.cfm?cat_id=683",
                            "category":"Advice",
                            "pubdate":"2014-11-24T23:04:00Z",
                            "alertLevel":"Advice",
                            "location":"Moppy Rd, Moppy, NSW 2422",
                            "councilArea":"Gloucester",
                            "status":"out of control",
                            "fireType":"Bush Fire",
                            "fire":true,
                            "size":"0 ha",
                            "responsibleAgency":"Rural Fire Service",
                            "extra":""
                        }
                    },
                    {
                        "type":"Feature",
                        "id":"94ce13db-8d7b-4eb7-a6aa-2b9e3741c60b",
                        "geometry":{
                            "type":"GeometryCollection",
                            "geometries":[
                                {
                                    "type":"Point",
                                    "coordinates":[
                                        151.6282,
                                        -31.9785
                                    ]
                                }
                            ]
                        },
                        "properties":{
                            "guid":"tag:www.rfs.nsw.gov.au,2014-11-25:179696",
                            "title":"Kerripit Fire",
                            "link":"http://www.rfs.nsw.gov.au/dsp_content.cfm?cat_id=683",
                            "category":"Advice",
                            "pubdate":"2014-11-24T23:04:00Z",
                            "alertLevel":"Advice",
                            "location":"Moppy Rd, Moppy, NSW 2422",
                            "councilArea":"Gloucester",
                            "status":"out of control",
                            "fireType":"Bush Fire",
                            "fire":true,
                            "size":"0 ha",
                            "responsibleAgency":"Rural Fire Service",
                            "extra":""
                        }
                    },
                    {
                        "type":"Feature",
                        "id":"8a367e50-cf85-44f5-9bdd-7038053e9766",
                        "geometry":{
                            "type":"GeometryCollection",
                            "geometries":[
                                {
                                    "type":"Point",
                                    "coordinates":[
                                        151.6653,
                                        -31.9857
                                    ]
                                },
                                {
                                    "type":"MultiPolygon",
                                    "coordinates":[
                                        [
                                            [
                                                [
                                                    151.6471,
                                                    -32.0003
                                                ],
                                                [
                                                    151.646,
                                                    -32.0009
                                                ],
                                                [
                                                    151.6445,
                                                    -32.0008
                                                ],
                                                [
                                                    151.6432,
                                                    -31.9992
                                                ],
                                                [
                                                    151.6432,
                                                    -31.9983
                                                ],
                                                [
                                                    151.644,
                                                    -31.9975
                                                ],
                                                [
                                                    151.6447,
                                                    -31.9973
                                                ],
                                                [
                                                    151.6457,
                                                    -31.9972
                                                ],
                                                [
                                                    151.6474,
                                                    -31.9978
                                                ],
                                                [
                                                    151.6477,
                                                    -31.9986
                                                ],
                                                [
                                                    151.6471,
                                                    -32.0003
                                                ]
                                            ]
                                        ]
                                    ]
                                }
                            ]
                        },
                        "properties":{
                            "guid":"tag:www.rfs.nsw.gov.au,2014-11-25:179696",
                            "title":"Kerripit Fire",
                            "link":"http://www.rfs.nsw.gov.au/dsp_content.cfm?cat_id=683",
                            "category":"Advice",
                            "pubdate":"2014-11-24T23:04:00Z",
                            "alertLevel":"Advice",
                            "location":"Moppy Rd, Moppy, NSW 2422",
                            "councilArea":"Gloucester",
                            "status":"out of control",
                            "fireType":"Bush Fire",
                            "fire":true,
                            "size":"0 ha",
                            "responsibleAgency":"Rural Fire Service",
                            "extra":""
                        }
                    }
                ]
            }
